steps:
- name: node:12
  entrypoint: yarn
  waitFor: ['-']
  id: 'yarnInstall'
- name: node:12
  entrypoint: yarn
  waitFor: ['yarnInstall']
  args: ["build:ui"]
  id: 'yarnBuild'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", ./packages/app/app.yaml]
  waitFor: ['yarnBuild']
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploySwapEndpoints'
  waitFor: ['yarnInstall']
  args:
    [
        'endpoints',
        'services',
        'deploy',
        './packages/swap-service/openapi.yaml',
    ]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
      [
          'app',
          'deploy',
          '--version=beta',
          './packages/swap-service/app.yaml',
      ]
  waitFor: ['deploySwapEndpoints']
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deployBotEndpoints'
  waitFor: ['yarnInstall']
  args:
    [
        'endpoints',
        'services',
        'deploy',
        './packages/bot/openapi.yaml',
    ]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
      [
          'app',
          'deploy',
          '--version=beta',
          './packages/bot/app.yaml',
      ]
  waitFor: ['deployBotEndpoints']

timeout: "1600s"